
[SupersonicTheme]
Name = "Catppuccin Frappé (Sky)"
Version = "0.2"
SupportsDark = true
SupportsLight = true


[LightColors]
PageBackground = "#EFF1F5FF"
ListHeader = "#DCE0E8FF"
PageHeader = "#E6E9EFFF"
Background = "#DCE0E8FF"
Button = "#E6E9EFFF"
DisabledButton = "#CCD0DAFF"
Disabled = "#4C4F69FF"
Error = "#D20F39FF"
Focus = "#C0E2F2FF"
Foreground = "#4C4F69FF"
ForegroundOnError = "#EFF1F5FF"
ForegroundOnPrimary = "#EFF1F5FF"
ForegroundOnSuccess = "#EFF1F5FF"
ForegroundOnWarning = "#EFF1F5FF"
HeaderBackground = "#CCD0DAFF"
Hover = "#D8E9F3FF"
Hyperlink = "#04A5E5FF"
InputBackground = "#E6E9EFFF"
InputBorder = "#CCD0DAFF"
MenuBackground = "#E6E9EFFF"
OverlayBackground = "#E6E9EFFF"
Placeholder = "#7C7F93FF"
Pressed = "#CCD0DA66"
Primary = "#04A5E5FF"
ScrollBar = "#E6E9EF99"
Selection = "#B4DEF1FF"
Separator = "#DCE0E8FF"
Success = "#40A02BFF"
Warning = "#DF8E1DFF"


[DarkColors]
PageBackground = "#303446FF"
ListHeader = "#232634FF"
PageHeader = "#292C3CFF"
Background = "#232634FF"
Button = "#292C3CFF"
DisabledButton = "#414559FF"
Disabled = "#C6D0F5FF"
Error = "#E78284FF"
Focus = "#455464FF"
Foreground = "#C6D0F5FF"
ForegroundOnError = "#303446FF"
ForegroundOnPrimary = "#303446FF"
ForegroundOnSuccess = "#303446FF"
ForegroundOnWarning = "#303446FF"
HeaderBackground = "#414559FF"
Hover = "#3A4354FF"
Hyperlink = "#99D1DBFF"
InputBackground = "#292C3CFF"
InputBorder = "#414559FF"
MenuBackground = "#292C3CFF"
OverlayBackground = "#292C3CFF"
Placeholder = "#949CBBFF"
Pressed = "#41455966"
Primary = "#99D1DBFF"
ScrollBar = "#292C3C99"
Selection = "#4A5B6BFF"
Separator = "#232634FF"
Success = "#A6D189FF"
Warning = "#E5C890FF"
