
[SupersonicTheme]
Name = "Catppuccin Frappé (Mauve)"
Version = "0.2"
SupportsDark = true
SupportsLight = true


[LightColors]
PageBackground = "#EFF1F5FF"
ListHeader = "#DCE0E8FF"
PageHeader = "#E6E9EFFF"
Background = "#DCE0E8FF"
Button = "#E6E9EFFF"
DisabledButton = "#CCD0DAFF"
Disabled = "#4C4F69FF"
Error = "#D20F39FF"
Focus = "#DACCF4FF"
Foreground = "#4C4F69FF"
ForegroundOnError = "#EFF1F5FF"
ForegroundOnPrimary = "#EFF1F5FF"
ForegroundOnSuccess = "#EFF1F5FF"
ForegroundOnWarning = "#EFF1F5FF"
HeaderBackground = "#CCD0DAFF"
Hover = "#E5DFF4FF"
Hyperlink = "#8839EFFF"
InputBackground = "#E6E9EFFF"
InputBorder = "#CCD0DAFF"
MenuBackground = "#E6E9EFFF"
OverlayBackground = "#E6E9EFFF"
Placeholder = "#7C7F93FF"
Pressed = "#CCD0DA66"
Primary = "#8839EFFF"
ScrollBar = "#E6E9EF99"
Selection = "#D5C3F4FF"
Separator = "#DCE0E8FF"
Success = "#40A02BFF"
Warning = "#DF8E1DFF"


[DarkColors]
PageBackground = "#303446FF"
ListHeader = "#232634FF"
PageHeader = "#292C3CFF"
Background = "#232634FF"
Button = "#292C3CFF"
DisabledButton = "#414559FF"
Disabled = "#C6D0F5FF"
Error = "#E78284FF"
Focus = "#4E4A66FF"
Foreground = "#C6D0F5FF"
ForegroundOnError = "#303446FF"
ForegroundOnPrimary = "#303446FF"
ForegroundOnSuccess = "#303446FF"
ForegroundOnWarning = "#303446FF"
HeaderBackground = "#414559FF"
Hover = "#3F3E56FF"
Hyperlink = "#CA9EE6FF"
InputBackground = "#292C3CFF"
InputBorder = "#414559FF"
MenuBackground = "#292C3CFF"
OverlayBackground = "#292C3CFF"
Placeholder = "#949CBBFF"
Pressed = "#41455966"
Primary = "#CA9EE6FF"
ScrollBar = "#292C3C99"
Selection = "#574F6EFF"
Separator = "#232634FF"
Success = "#A6D189FF"
Warning = "#E5C890FF"
