[SupersonicTheme]
Name = "Catppuccin Frappé (Sky)"
Version = "0.2"
SupportsDark = true
SupportsLight = false

[DarkColors]
PageBackground = "#303446FF"
ListHeader = "#232634FF"
PageHeader = "#292C3CFF"
Background = "#232634FF"
Button = "#292C3CFF"
DisabledButton = "#414559FF"
Disabled = "#C6D0F5FF"
Error = "#E78284FF"
Focus = "#455464FF"
Foreground = "#C6D0F5FF"
ForegroundOnError = "#303446FF"
ForegroundOnPrimary = "#303446FF"
ForegroundOnSuccess = "#303446FF"
ForegroundOnWarning = "#303446FF"
HeaderBackground = "#414559FF"
Hover = "#3A4354FF"
Hyperlink = "#99D1DBFF"
InputBackground = "#292C3CFF"
InputBorder = "#414559FF"
MenuBackground = "#292C3CFF"
OverlayBackground = "#292C3CFF"
Placeholder = "#949CBBFF"
Pressed = "#41455966"
Primary = "#99D1DBFF"
ScrollBar = "#292C3C99"
Selection = "#4A5B6BFF"
Separator = "#232634FF"
Success = "#A6D189FF"
Warning = "#E5C890FF"
