
[SupersonicTheme]
Name = "Catppuccin Macchiato (Sky)"
Version = "0.2"
SupportsDark = true
SupportsLight = true


[LightColors]
PageBackground = "#EFF1F5FF"
ListHeader = "#DCE0E8FF"
PageHeader = "#E6E9EFFF"
Background = "#DCE0E8FF"
Button = "#E6E9EFFF"
DisabledButton = "#CCD0DAFF"
Disabled = "#4C4F69FF"
Error = "#D20F39FF"
Focus = "#C0E2F2FF"
Foreground = "#4C4F69FF"
ForegroundOnError = "#EFF1F5FF"
ForegroundOnPrimary = "#EFF1F5FF"
ForegroundOnSuccess = "#EFF1F5FF"
ForegroundOnWarning = "#EFF1F5FF"
HeaderBackground = "#CCD0DAFF"
Hover = "#D8E9F3FF"
Hyperlink = "#04A5E5FF"
InputBackground = "#E6E9EFFF"
InputBorder = "#CCD0DAFF"
MenuBackground = "#E6E9EFFF"
OverlayBackground = "#E6E9EFFF"
Placeholder = "#7C7F93FF"
Pressed = "#CCD0DA66"
Primary = "#04A5E5FF"
ScrollBar = "#E6E9EF99"
Selection = "#B4DEF1FF"
Separator = "#DCE0E8FF"
Success = "#40A02BFF"
Warning = "#DF8E1DFF"


[DarkColors]
PageBackground = "#24273AFF"
ListHeader = "#181926FF"
PageHeader = "#1E2030FF"
Background = "#181926FF"
Button = "#1E2030FF"
DisabledButton = "#363A4FFF"
Disabled = "#CAD3F5FF"
Error = "#ED8796FF"
Focus = "#3A4A5BFF"
Foreground = "#CAD3F5FF"
ForegroundOnError = "#24273AFF"
ForegroundOnPrimary = "#24273AFF"
ForegroundOnSuccess = "#24273AFF"
ForegroundOnWarning = "#24273AFF"
HeaderBackground = "#363A4FFF"
Hover = "#2E384AFF"
Hyperlink = "#91D7E3FF"
InputBackground = "#1E2030FF"
InputBorder = "#363A4FFF"
MenuBackground = "#1E2030FF"
OverlayBackground = "#1E2030FF"
Placeholder = "#939AB7FF"
Pressed = "#363A4F66"
Primary = "#91D7E3FF"
ScrollBar = "#1E203099"
Selection = "#3F5364FF"
Separator = "#181926FF"
Success = "#A6DA95FF"
Warning = "#EED49FFF"
