[SupersonicTheme]
Name = "Catppuccin Macchiato (Rosewater)"
Version = "0.2"
SupportsDark = true
SupportsLight = false

[DarkColors]
PageBackground = "#24273AFF"
ListHeader = "#181926FF"
PageHeader = "#1E2030FF"
Background = "#181926FF"
Button = "#1E2030FF"
DisabledButton = "#363A4FFF"
Disabled = "#CAD3F5FF"
Error = "#ED8796FF"
Focus = "#4E4B59FF"
Foreground = "#CAD3F5FF"
ForegroundOnError = "#24273AFF"
ForegroundOnPrimary = "#24273AFF"
ForegroundOnSuccess = "#24273AFF"
ForegroundOnWarning = "#24273AFF"
HeaderBackground = "#363A4FFF"
Hover = "#383849FF"
Hyperlink = "#F4DBD6FF"
InputBackground = "#1E2030FF"
InputBorder = "#363A4FFF"
MenuBackground = "#1E2030FF"
OverlayBackground = "#1E2030FF"
Placeholder = "#939AB7FF"
Pressed = "#363A4F66"
Primary = "#F4DBD6FF"
ScrollBar = "#1E203099"
Selection = "#585461FF"
Separator = "#181926FF"
Success = "#A6DA95FF"
Warning = "#EED49FFF"
