[SupersonicTheme]
Name = "Catppuccin Macchiato (Blue)"
Version = "0.2"
SupportsDark = true
SupportsLight = false

[DarkColors]
PageBackground = "#24273AFF"
ListHeader = "#181926FF"
PageHeader = "#1E2030FF"
Background = "#181926FF"
Button = "#1E2030FF"
DisabledButton = "#363A4FFF"
Disabled = "#CAD3F5FF"
Error = "#ED8796FF"
Focus = "#39425FFF"
Foreground = "#CAD3F5FF"
ForegroundOnError = "#24273AFF"
ForegroundOnPrimary = "#24273AFF"
ForegroundOnSuccess = "#24273AFF"
ForegroundOnWarning = "#24273AFF"
HeaderBackground = "#363A4FFF"
Hover = "#2E344CFF"
Hyperlink = "#8AADF4FF"
InputBackground = "#1E2030FF"
InputBorder = "#363A4FFF"
MenuBackground = "#1E2030FF"
OverlayBackground = "#1E2030FF"
Placeholder = "#939AB7FF"
Pressed = "#363A4F66"
Primary = "#8AADF4FF"
ScrollBar = "#1E203099"
Selection = "#3E4868FF"
Separator = "#181926FF"
Success = "#A6DA95FF"
Warning = "#EED49FFF"
