[SupersonicTheme]
Name = "Catppuccin Macchiato (Sky)"
Version = "0.2"
SupportsDark = true
SupportsLight = false

[DarkColors]
PageBackground = "#24273AFF"
ListHeader = "#181926FF"
PageHeader = "#1E2030FF"
Background = "#181926FF"
Button = "#1E2030FF"
DisabledButton = "#363A4FFF"
Disabled = "#CAD3F5FF"
Error = "#ED8796FF"
Focus = "#3A4A5BFF"
Foreground = "#CAD3F5FF"
ForegroundOnError = "#24273AFF"
ForegroundOnPrimary = "#24273AFF"
ForegroundOnSuccess = "#24273AFF"
ForegroundOnWarning = "#24273AFF"
HeaderBackground = "#363A4FFF"
Hover = "#2E384AFF"
Hyperlink = "#91D7E3FF"
InputBackground = "#1E2030FF"
InputBorder = "#363A4FFF"
MenuBackground = "#1E2030FF"
OverlayBackground = "#1E2030FF"
Placeholder = "#939AB7FF"
Pressed = "#363A4F66"
Primary = "#91D7E3FF"
ScrollBar = "#1E203099"
Selection = "#3F5364FF"
Separator = "#181926FF"
Success = "#A6DA95FF"
Warning = "#EED49FFF"
