[SupersonicTheme]
Name = "Catppuccin Mocha (Peach)"
Version = "0.2"
SupportsDark = true
SupportsLight = false

[DarkColors]
PageBackground = "#1E1E2EFF"
ListHeader = "#11111BFF"
PageHeader = "#181825FF"
Background = "#11111BFF"
Button = "#181825FF"
DisabledButton = "#313244FF"
Disabled = "#CDD6F4FF"
Error = "#F38BA8FF"
Focus = "#4A3C40FF"
Foreground = "#CDD6F4FF"
ForegroundOnError = "#1E1E2EFF"
ForegroundOnPrimary = "#1E1E2EFF"
ForegroundOnSuccess = "#1E1E2EFF"
ForegroundOnWarning = "#1E1E2EFF"
HeaderBackground = "#313244FF"
Hover = "#342D36FF"
Hyperlink = "#FAB387FF"
InputBackground = "#181825FF"
InputBorder = "#313244FF"
MenuBackground = "#181825FF"
OverlayBackground = "#181825FF"
Placeholder = "#9399B2FF"
Pressed = "#31324466"
Primary = "#FAB387FF"
ScrollBar = "#18182599"
Selection = "#554344FF"
Separator = "#11111BFF"
Success = "#A6E3A1FF"
Warning = "#F9E2AFFF"
